# Generated by Django 3.1 on 2021-04-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_contact', '0005_remove_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
