# Generated by Django 3.1 on 2021-01-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_info', '0006_personalinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='facebook',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
