# Generated by Django 3.1 on 2021-01-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_info', '0007_personalinfo_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
