# Generated by Django 3.1 on 2021-01-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_info', '0008_personalinfo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='twitter',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
