# Generated by Django 3.1 on 2021-01-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_info', '0009_auto_20210121_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
