# Generated by Django 3.1 on 2021-04-11 00:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_info', '0010_auto_20210121_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
